name: Soundboard
main: com.aegamesi.mc.soundboard.SoundboardPlugin
version: 1.2
authors: [PickleMan, aegamesi, admin.aegamesi@gmail.com]
description: Soundboard stuff

commands:
    sb:
        description: Use this to access all the Soundboard commands
        usage: /<command>
        
permissions:
   soundboard.*:
      description: Allows you to use soundboard
      default: false