name: Soundboard
main: com.aegamesi.mc.soundboard.SoundboardPlugin
version: 1.2
authors: [PickleMan, aegamesi, admin.aegamesi@gmail.com]
description: Soundboard stuff

commands:
    sb:
        description: Use this to access all the Soundboard commands
        usage: /<command>
        
permissions:
   soundboard.main:
      description: Allows you to use soundboard
      default: false
   soundboard.target.self:
      description: Allows you to use target self
      default: false
   soundboard.target.self_only:
      description: Allows you to use target self_only
      default: false
   soundboard.target.player:
      description: Allows you to use target player
      default: false
   soundboard.target.player_only:
      description: Allows you to use target player_only
      default: false
   soundboard.target.location:
      description: Allows you to use target location
      default: false
   soundboard.target.all:
      description: Allows you to use target all
      default: false